# Generated by Django 5.1.5 on 2025-01-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='status',
            field=models.CharField(choices=[('df', 'Draft'), ('pd', 'Published')], default='df', max_length=2),
        ),
    ]
